# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Mar 14 00:22:29 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(552, 459)
        MainWindow.setMaximumSize(QtCore.QSize(552, 500))
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        MainWindow.setStyleSheet(_fromUtf8("#centralWidget {\n"
"    background-image: url(:/new/images/bg7.png); \n"
"}"))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("B Nazanin+ Regular"))
        self.groupBox.setFont(font)
        self.groupBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setMinimumSize(QtCore.QSize(69, 0))
        self.label.setMaximumSize(QtCore.QSize(69, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("B Nazanin+ Regular"))
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setMinimumSize(QtCore.QSize(69, 0))
        self.label_2.setMaximumSize(QtCore.QSize(69, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("B Nazanin+ Regular"))
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.text_input = QtGui.QLineEdit(self.groupBox)
        self.text_input.setObjectName(_fromUtf8("text_input"))
        self.verticalLayout_2.addWidget(self.text_input)
        self.text_output = QtGui.QLineEdit(self.groupBox)
        self.text_output.setObjectName(_fromUtf8("text_output"))
        self.verticalLayout_2.addWidget(self.text_output)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btn_browse_input = QtGui.QPushButton(self.groupBox)
        self.btn_browse_input.setMaximumSize(QtCore.QSize(29, 16777215))
        self.btn_browse_input.setObjectName(_fromUtf8("btn_browse_input"))
        self.gridLayout.addWidget(self.btn_browse_input, 0, 0, 1, 1)
        self.btn_browse_output = QtGui.QPushButton(self.groupBox)
        self.btn_browse_output.setMaximumSize(QtCore.QSize(29, 16777215))
        self.btn_browse_output.setObjectName(_fromUtf8("btn_browse_output"))
        self.gridLayout.addWidget(self.btn_browse_output, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 2, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(61, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_segmentation = QtGui.QPushButton(self.groupBox)
        self.btn_segmentation.setMaximumSize(QtCore.QSize(114, 49))
        self.btn_segmentation.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("run.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_segmentation.setIcon(icon)
        self.btn_segmentation.setIconSize(QtCore.QSize(50, 50))
        self.btn_segmentation.setAutoDefault(True)
        self.btn_segmentation.setDefault(False)
        self.btn_segmentation.setFlat(True)
        self.btn_segmentation.setObjectName(_fromUtf8("btn_segmentation"))
        self.horizontalLayout.addWidget(self.btn_segmentation)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 3)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("B Nazanin+ Regular"))
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setMinimumSize(QtCore.QSize(71, 0))
        self.label_3.setMaximumSize(QtCore.QSize(71, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("B Nazanin+ Regular"))
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.text_cores = QtGui.QLineEdit(self.groupBox_2)
        self.text_cores.setObjectName(_fromUtf8("text_cores"))
        self.horizontalLayout_2.addWidget(self.text_cores)
        self.btn_browse_cores = QtGui.QPushButton(self.groupBox_2)
        self.btn_browse_cores.setMaximumSize(QtCore.QSize(29, 16777215))
        self.btn_browse_cores.setObjectName(_fromUtf8("btn_browse_cores"))
        self.horizontalLayout_2.addWidget(self.btn_browse_cores)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setMinimumSize(QtCore.QSize(71, 0))
        self.label_5.setMaximumSize(QtCore.QSize(71, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("B Nazanin+ Regular"))
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.text_target = QtGui.QLineEdit(self.groupBox_2)
        self.text_target.setObjectName(_fromUtf8("text_target"))
        self.horizontalLayout_6.addWidget(self.text_target)
        self.btn_browse_target = QtGui.QPushButton(self.groupBox_2)
        self.btn_browse_target.setMaximumSize(QtCore.QSize(29, 16777215))
        self.btn_browse_target.setObjectName(_fromUtf8("btn_browse_target"))
        self.horizontalLayout_6.addWidget(self.btn_browse_target)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.btn_learn = QtGui.QPushButton(self.groupBox_2)
        self.btn_learn.setMinimumSize(QtCore.QSize(0, 53))
        self.btn_learn.setText(_fromUtf8(""))
        self.btn_learn.setIcon(icon)
        self.btn_learn.setIconSize(QtCore.QSize(50, 50))
        self.btn_learn.setFlat(True)
        self.btn_learn.setObjectName(_fromUtf8("btn_learn"))
        self.horizontalLayout_3.addWidget(self.btn_learn)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.centralWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("B Nazanin+ Regular"))
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setMinimumSize(QtCore.QSize(71, 0))
        self.label_4.setMaximumSize(QtCore.QSize(71, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("B Nazanin+ Regular"))
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.text_sample = QtGui.QLineEdit(self.groupBox_3)
        self.text_sample.setObjectName(_fromUtf8("text_sample"))
        self.horizontalLayout_4.addWidget(self.text_sample)
        self.btn_browse_sample = QtGui.QPushButton(self.groupBox_3)
        self.btn_browse_sample.setMaximumSize(QtCore.QSize(29, 16777215))
        self.btn_browse_sample.setObjectName(_fromUtf8("btn_browse_sample"))
        self.horizontalLayout_4.addWidget(self.btn_browse_sample)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.btn_test = QtGui.QPushButton(self.groupBox_3)
        self.btn_test.setMinimumSize(QtCore.QSize(0, 48))
        self.btn_test.setText(_fromUtf8(""))
        self.btn_test.setIcon(icon)
        self.btn_test.setIconSize(QtCore.QSize(50, 50))
        self.btn_test.setFlat(True)
        self.btn_test.setObjectName(_fromUtf8("btn_test"))
        self.horizontalLayout_5.addWidget(self.btn_test)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 1, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "استخراج هسته ها", None))
        self.label.setText(_translate("MainWindow", "آدرس تصاویر", None))
        self.label_2.setText(_translate("MainWindow", "آدرس خروجی", None))
        self.btn_browse_input.setText(_translate("MainWindow", "...", None))
        self.btn_browse_output.setText(_translate("MainWindow", "...", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "یادگیری   ", None))
        self.label_3.setText(_translate("MainWindow", "آدرس نمونه ها", None))
        self.btn_browse_cores.setText(_translate("MainWindow", "...", None))
        self.label_5.setText(_translate("MainWindow", "آدرس نمونه ها", None))
        self.btn_browse_target.setText(_translate("MainWindow", "...", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "آزمون    ", None))
        self.label_4.setText(_translate("MainWindow", "آدرس تصویر", None))
        self.btn_browse_sample.setText(_translate("MainWindow", "...", None))

